cmdargs:
    # Checking more strictly
    severity: style_problem

policies:
    # Disable a violation
    ProhibitUnnecessaryDoubleQuote:
        enabled: false
    ProhibitImplicitScopeVariable:
        enabled: false
