#!/bin/sh
set -e

cd ~/.vim_runtime

echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim
" See ~/.vim_runtime/README.md "How to include your own stuff" for further options.

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

let files=glob("~/.vim_runtime/my_configs/*.vim", 1, 1)
if empty(files)
  try
    source ~/.vim_runtime/my_configs.vim
  catch
  endtry
else
  for file in files
    try
      execute 'source' fnameescape(file)
    catch
    endtry
  endfor
endif' > ~/.vimrc

echo "Installed the Ultimate Vim configuration successfully! Enjoy :-)"
