set nocompatible
set rtp+=../
set rtp+=../build/tabular/
set rtp+=../build/vim-toml/
set rtp+=../build/vim-json/
set rtp+=../build/vader.vim/
set rtp-=~/.vim
set rtp-=~/.vim/after
let $LANG='en_US'
filetype on
filetype plugin on
filetype indent on
syntax on

function! Markdown_GetScriptID(fname) abort
    let l:snlist = ''
    redir => l:snlist
    silent! scriptnames
    redir END
    let l:mx = '^\s*\(\d\+\):\s*\(.*\)$'
    for l:line in split(l:snlist, "\n")
        if stridx(substitute(l:line, '\\', '/', 'g'), a:fname) >= 0
            return substitute(l:line, l:mx, '\1', '')
        endif
    endfor
endfunction
function! Markdown_GetFunc(fname, funcname) abort
    return function('<SNR>' . Markdown_GetScriptID(a:fname) . '_' . a:funcname)
endfunction
