version: "2"
services:
  vim:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root/vim-elixir
    working_dir: /root/vim-elixir
  nvim:
    build:
      context: .
      dockerfile: Dockerfile.nvim
    volumes:
      - .:/root/vim-elixir
    working_dir: /root/vim-elixir
