language: go
notifications:
  email: false
matrix:
  include:
    - env: SCRIPT=test VIM_VERSION=vim-7.4
    - env: SCRIPT=test VIM_VERSION=vim-8.0
    - env: SCRIPT=test VIM_VERSION=nvim
    - env: SCRIPT=lint VIM_VERSION=vim-8.0
install:
  - ./scripts/install-vim $VIM_VERSION
  - pip install --user vim-vint
script:
  - ./scripts/$SCRIPT $VIM_VERSION
