language: vim

os:
  - linux
  - osx

env:
  - TEST=package
  - TEST=latest

before_script: |
  if [ "$TEST" = "package" ]; then
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get -y update
      sudo apt-get -y install vim
    fi
  else
    cd ..
    git clone --depth 1 https://github.com/vim/vim
    cd vim
    ./configure --with-features=huge
    make
    sudo make install
    export PATH="/usr/local/bin:$PATH"
    cd "$TRAVIS_BUILD_DIR"
  fi
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    sudo -H easy_install pip
  fi
  sudo -H pip install virtualenv

script:
  - make test
  - make doc
